services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - WATCHFILES_FORCE_POLLING=true
    env_file:
      - .env
    networks:
      - queue-net

  # Audio Analytics (Django) service
  audio-analysis:
    build: ./audio_analysis
    volumes:
      - ./audio_analysis:/usr/src/app
    ports:
      - "8003:8003"
    networks:
      - queue-net

  frontend:
    build:
      context: ./frontend
      target: development # Dev stage using Vite
      args:
        VITE_API_URL: http://localhost:8000
        VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
    env_file:
      - .env
    networks:
      - queue-net

  nginx:
    profiles: ["production"]

networks:
  queue-net:
    driver: bridge