server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://frontend:80/;
    }

    location /api/ {
        proxy_pass http://backend:8000/;
    }

    location /inscriber/ {
        proxy_pass http://inscriber:8002/;
    }

    location /session/ {
        try_files $uri $uri/ /index.html;
    }
}