# server {
#     listen 80;
#     server_name localhost;

#     location / {
#         proxy_pass http://frontend:80/;
#     }

#     location /api/ {
#         proxy_pass http://backend:8000/;
#     }

#     location /inscriber/ {
#         proxy_pass http://inscriber:8002/;
#     }

#     location /session/ {
#         try_files $uri $uri/ /index.html;
#     }
# }

server {
    listen 80;
    server_name reviewanalysis.uxlivinglab.org;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name reviewanalysis.uxlivinglab.org;

    ssl_certificate /etc/letsencrypt/live/reviewanalysis.uxlivinglab.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/reviewanalysis.uxlivinglab.org/privkey.pem;

    location / {
        proxy_pass http://frontend:80/;
    }

    location /api/ {
        proxy_pass http://backend:8000/;
    }

    location /inscriber/ {
        proxy_pass http://inscriber:8002/;
    }

    location /session/ {
        try_files $uri $uri/ /index.html;
    }
}